version: '3'
services:
  # web:
  #   image: nginx:${NGINX_VERSION}
  #   restart: always
  #   ports:
  #     - "${HOST_PORT}:80"
  #   links:
  #     - server
  #   container_name: ${PRE_NAME}-web
  #   volumes:
  #     - ./nginx/html:/usr/share/nginx/html
  #     - ./nginx/logs:/var/log/nginx
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/conf:/etc/nginx/conf.d
  # server:
  #   build: ./server/DockerFile
  #   restart: always
  #   container_name: ${PRE_NAME}-server
  #   depends_on:
  #     - mongo
  #     - redis
  #   ports:
  #     - "7001:7004"
  #   links:
  #     - mongo
  #     - redis
  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    container_name: ${PRE_NAME}-redis
    command: --requirepass ${REDIS_ROOT_PASSWORD}  --appendonly yes
    volumes:
      # - ./etc/localtime:/etc/localtime:ro
      - ./redis/data:/data

  mongo:
    image: mongo:${MongoDB_VERSION}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MongoDB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MongoDB_PASSWORD}
    ports:
      - "${MongoDB_PORT}:27017"
    volumes:
      - ./mongodb/db:/data/db
      